### PR TITLE
'ascii' codec can't decode byte 0xa0 - part 2

### PR DESCRIPTION
**Pull request by eider-i128**
So... It still doesn't work as expected after v181 update :(

https://github.com/hydrusnetwork/hydrus/issues/74

### CODE REVIEW

**Comment by hydrusnetwork** [comment]
I'm sorry about this. I'll put together a hotfix now.

**Comment by hydrusnetwork** [comment]
For my own interest, what do you get if you put:

locale.format( u'%d', 123456, grouping = True )

into a python terminal? Does it come back as raw bytes, or does it throw an exception?

**Comment by eider-i128** [comment]
>>> locale.setlocale(locale.LC_ALL, '')
'Polish_Poland.1250'

>>> locale.format( u'%d', 123456, grouping = True )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\locale.py", line 196, in format
    return _format(percent, value, grouping, monetary, *additional)
  File "C:\Python27\lib\locale.py", line 217, in _format
    formatted, seps = _group(formatted, monetary=monetary)
  File "C:\Python27\lib\locale.py", line 166, in _group
    left_spaces + thousands_sep.join(groups) + right_spaces,
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 0: ordinal not in range(128)

>>> locale.format( '%d', 123456, grouping = True ).decode(locale.getlocale()[1])
u'123\xa0456'

**Comment by hydrusnetwork** [comment]
Wow, inside the library! Thank you--the updated exe and zip is uploading to github now.

**Comment by eider-i128** [comment]
Fixed by latest hotfix.

**Pull request closed without merging**
