### PR TITLE
Add support for Krita files

### PR DESCRIPTION
**Pull request by Minnowo**
Adds support for Krita files. They have the extension `.kra` and `.krz`.
They are just zip files with a different file extension, but I was able to identify them consistently with their header which is just their mime type `application/x-krita`.

It is relatively easy to get information about the file, inside the zip there is `maindoc.xml` and `documentinfo.xml` which contain a bunch of information. I only make use of the width and height but stuff like author, title and comment as well as animation info would be cool to put into notes or the exif tab.

The `.kra` files contain `preview.png` and `mergedimage.png` (`.krz` only contains `preview.png`), which is a thumbnail and full resolution image of all the merged layers which allow for easy thumbnail generation.

(This is for Krita 5, I'm not sure if it works on older versions.)

### CODE REVIEW

**Comment by floogulinc** [comment]
The generic icon should be a 200x200px PNG preferably to match the rest.

**Comment by floogulinc** [comment]
Also the ZIP handling functions should probably be broken out into their own thing so they can be reused for other filetypes.

**Comment by Minnowo** [comment]
> Also the ZIP handling functions should probably be broken out into their own thing so they can be reused for other filetypes.

Could you clarify what you mean by this? My first thought is moving `ExtractSingleFileFromZip` into either `HydrusData`, `HydrusCompression` or creating a new file altogether.

**Comment by hydrusnetwork** [comment]
Thank you, this looks excellent and all fits into my code great. Don't worry about the zip refactoring stuff. I haven't got started on any proper zip infrastructure, but at some point I'll figure out a HydrusArchive.py or something, and I can move it over myself.

**Pull request merged**
