### PR TITLE
Fix the application icon on KDE Plasma Wayland

### PR DESCRIPTION
**Pull request by aidanharris**
This fixes the application icon on KDE Plasma Wayland (tested on Plasma 6) and possibly other Wayland compositors too.

The desktop filename was chosen because this is the identifier that the Hydrus Flatpak application uses.

Distribution packagers should make sure that this name matches with the desktop file that they install (for example, Gentoo installs a /usr/share/applications/hydrus-client-hydrus.desktop file).

It is strongly suggested that distributions install their Hydrus .desktop file at
/usr/share/applications/io.github.hydrusnetwork.hydrus.desktop to avoid needing to apply extra patches, etc.

## Before

Screenshot_20240320_073552

## After

Screenshot_20240320_075935

### CODE REVIEW

**Comment by aidanharris** [comment]
> Have you tested whether this changes anything for Windows or macOS?

I haven't. I don't expect it will because they don't use the Freedesktop desktop entry standard for anything but I don't know how this is handled on the Qt side on these platforms.

Does setDesktopFileName turn into a noop? Or does it throw an Exception, etc? I don't know.

**Comment by floogulinc** [comment]
After looking at the docs for that function I'm guessing you're right and it won't affect anything else.

**Comment by aidanharris** [comment]
One thing I've not addressed is if Hydrus should rename ~/.local/share/applications/hydrus.desktop to  ~/.local/share/applications/hydrus.desktop ~/.local/share/applications/io.github.hydrusnetwork.hydrus.desktop

Given this has always been broken, I think there's no harm doing nothing and letting the user re-name it manually (they'd have had to have made that .desktop entry manually anyway).

This only matters for people that installed Hydrus manually.

We could do a migration to re-name this though but I'm not sure where the best place to put it would be.

The logic would be something like:

```python
if os.name == 'posix' and platform.system() != 'Darwin':
  old_desktop = os.path.expanduser('~/.local/share/applications/hydrus.desktop')
  new_desktop = os.path.expanduser('~/.local/share/applications/io.github.hydrusnetwork.hydrus.desktop')
  if os.path.exists(old_desktop) and not os.path.exists(new_desktop):
    os.rename(old_desktop, new_desktop)

**Comment by hydrusnetwork** [comment]
Thank you very much for this work! I don't know much about Linux, so this is appreciated. Just to be safe, I think I'll wrap that `setDesktopFileName` call in a 'are we running Linux?' test, since I assume this doesn't do anything on Win/macOS anyway.

I agree we shouldn't rename this stuff manually. Let the user figure things out for their situation.

**Pull request merged**
