### PR TITLE
Created module packaging

### PR DESCRIPTION
**Pull request by Cerberus1746**
Hello! I stumbled upon your package and I found it really awesome!
But I was having issues with the installation having to install one package at a time, so I made a setup.py with requirements file and stuff, it's ready to upload to pip too. So i figure out I would try and create a pull request for it :3

But you need to change the author and author email variables inside setup.py cause for now I left blank.

### CODE REVIEW

**Comment by Ryonez** [comment]
Okay, so just a heads up, the dev doesn't do pull requests here. He on the ball thought, and you can reach him over on the discord for suggestions.

As to package installation, there is none. Everything is included in the release packages, should be as simple as extracting and running hydrus.

**Comment by Cerberus1746** [comment]
> Okay, so just a heads up, the dev doesn't do pull requests here. He's on the ball thought, and you can reach him over on the discord for suggestions.

Oh! Thanks for the info ^^
> As to package installation, there is none. Everything is included in the release packages, should be as simple as extracting and running hydrus.

Oh, yes, I am aware. Unless you are running it directly with python from the repo, so you still need to install in python the dependencies, I for example was interested in the app to create categories and tagging to study AI so I would need to change the source or use hydrus as a dependency, so in my case for example. Having a packaging or the requirements files helps a lot.

**Comment by rachmadaniHaryono** [comment]
>pr

maybe it is possible to keep the `include` folder name similar to this `src` case https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure

>use hydrus as a dependency, 

i don't think hydrus is ready to be used as library but i am interested if there is example for this

---

also note that there is other installation method other than run the executable or guide on help page

- Client VNC: https://hub.docker.com/r/legsplits/hydrus/
- Server: https://hub.docker.com/r/mserajnik/hydrus-server-docker/
- aur: https://aur.archlinux.org/packages/hydrus/

**Comment by DonaldTsang** [comment]
@Cerberus1746 could you please update your code to be as close to the current version of Hydrus as possible? and then get on https://discord.gg/vy8CUB4 to talk to the dev team?

**Pull request closed without merging**
